# Generated by Django 5.1.3 on 2024-12-04 18:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_compra_fecha_compra_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='fecha_compra',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='fecha_venta',
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
