# Generated by Django 5.1.3 on 2025-01-24 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0014_alter_venta_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
    ]
