# Generated by Django 5.1.3 on 2025-01-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0016_detalleventa_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cantidad',
            field=models.CharField(default=0.0, max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='venta',
            name='total_producto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
    ]
