# Generated by Django 5.1.3 on 2025-01-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0017_venta_cantidad_venta_precio_venta_producto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total_producto',
            field=models.CharField(default='', max_length=255),
        ),
    ]
